// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
	"github.com/shopspring/decimal"
)

type OutboxStatus string

const (
	OutboxStatusPENDING OutboxStatus = "PENDING"
	OutboxStatusSENT    OutboxStatus = "SENT"
	OutboxStatusFAILED  OutboxStatus = "FAILED"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type PaymentCurrency string

const (
	PaymentCurrencyETB PaymentCurrency = "ETB"
	PaymentCurrencyUSD PaymentCurrency = "USD"
)

func (e *PaymentCurrency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentCurrency(s)
	case string:
		*e = PaymentCurrency(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentCurrency: %T", src)
	}
	return nil
}

type NullPaymentCurrency struct {
	PaymentCurrency PaymentCurrency
	Valid           bool // Valid is true if PaymentCurrency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentCurrency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentCurrency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentCurrency), nil
}

type PaymentStatus string

const (
	PaymentStatusPENDING PaymentStatus = "PENDING"
	PaymentStatusSUCCESS PaymentStatus = "SUCCESS"
	PaymentStatusFAILED  PaymentStatus = "FAILED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type OutboxEvent struct {
	ID        uuid.UUID
	Payload   pgtype.JSONB
	Status    OutboxStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Payment struct {
	ID        uuid.UUID
	Reference uuid.UUID
	Amount    decimal.Decimal
	Currency  PaymentCurrency
	Status    PaymentStatus
	CreatedAt time.Time
	UpdatedAt time.Time
}
