// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox_events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (payload, status, created_at, updated_at)
VALUES ($1, $2, $3, $3)
RETURNING id, payload, status, created_at, updated_at
`

type CreateOutboxEventParams struct {
	Payload   pgtype.JSONB
	Status    OutboxStatus
	CreatedAt time.Time
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent, arg.Payload, arg.Status, arg.CreatedAt)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOutboxEvent = `-- name: DeleteOutboxEvent :execrows
DELETE FROM outbox_events WHERE id = $1
`

func (q *Queries) DeleteOutboxEvent(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOutboxEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPendingOutboxEventsForUpdate = `-- name: GetPendingOutboxEventsForUpdate :many
SELECT id, payload, status, created_at, updated_at
FROM outbox_events
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingOutboxEventsForUpdate(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, getPendingOutboxEventsForUpdate, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvent
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutboxStatus = `-- name: UpdateOutboxStatus :execrows
UPDATE outbox_events
SET
    status = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateOutboxStatusParams struct {
	ID        uuid.UUID
	Status    OutboxStatus
	UpdatedAt time.Time
}

func (q *Queries) UpdateOutboxStatus(ctx context.Context, arg UpdateOutboxStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOutboxStatus, arg.ID, arg.Status, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
